= cargo-cmake-vcpkg

== Setup

....
git clone --recurse-submodules https://github.com/mehmetoguzderin/cargo-cmake-vcpkg
cd cargo-cmake-vcpkg
conda env create --prefix ./.conda -f environment.yml
conda activate ./.conda
....

=== Codespaces

....
apt update
apt install cargo clang cmake curl git ninja-build pkg-config rustc tar unzip wget zip
git submodule update --init --recursive
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh
....

== Configure

....
cmake -G Ninja -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build
....

=== Windows

....
cmake -A x64 -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows -S ./ -B ./build
....

== Build

....
cmake --build ./build
....

=== Windows

....
cmake --build ./build --config Release
....

== Run

....
cd build
./main-rs
....

=== Windows

....
cd build/Release
../main-rs.exe
....
